T3/Areas/Templates/Pages/BufferedMultipleFileUploadDb.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Configuration;
using T3.Areas.Templates.Data;
using T3.Data;
using T3.Utilities;

namespace T3.Areas.Templates.Pages
{
    public class BufferedMultipleFileUploadDbModel : PageModel
    {
        private readonly ApplicationDbContext _context;
        private readonly long _fileSizeLimit;
        private readonly string[] _permittedExtensions = { ".jpg", ".png",".txt", ".xlsx" };

        public BufferedMultipleFileUploadDbModel(ApplicationDbContext context, 
            IConfiguration config)
        {
            _context = context;
            _fileSizeLimit = config.GetValue<long>("FileSizeLimit");
        }

        [BindProperty]
        public BufferedMultipleFileUploadDb FileUpload { get; set; }

        public string Result { get; private set; }

        public void OnGet()
        {
        }

        public async Task<IActionResult> OnPostUploadAsync()
        {
            // Perform an initial check to catch FileUpload class
            // attribute violations.
            if (!ModelState.IsValid)
            {
                Result = "Please correct the form.";

                return Page();
            }

            foreach (var formFile in FileUpload.FormFiles)
            {
                var formFileContent = 
                    await FileHelpers.ProcessFormFile<BufferedMultipleFileUploadDb>(
                        formFile, ModelState, _permittedExtensions, 
                        _fileSizeLimit);

                // Perform a second check to catch ProcessFormFile method
                // violations. If any validation check fails, return to the
                // page.
                if (!ModelState.IsValid)
                {
                    Result = "Please correct the form.";

                    return Page();
                }

                // **WARNING!**
                // In the following example, the file is saved without
                // scanning the file's contents. In most production
                // scenarios, an anti-virus/anti-malware scanner API
                // is used on the file before making the file available
                // for download or for use by other systems. 
                // For more information, see the topic that accompanies 
                // this sample.

                var file = new Template()
                {
                    Content = formFileContent, 
                    UntrustedName = formFile.FileName, 
                    Note = FileUpload.Note,
                    Size = formFile.Length, 
                    UploadDT = DateTime.UtcNow
                };

                _context.Templates.Add(file);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }

    public class BufferedMultipleFileUploadDb
    {
        [Required]
        [Display(Name="File")]
        public List<IFormFile> FormFiles { get; set; }

        [Display(Name="Note")]
        [StringLength(50, MinimumLength = 0)]
        public string Note { get; set; }
    }
}

T3/Areas/Templates/Pages/Index.cshtml.cs
using System.Collections.Generic;
using System.IO;
using System.Net;
using System.Net.Mime;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.FileProviders;
using T3.Areas.Templates.Data;
using T3.Data;

namespace T3.Areas.Templates.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ApplicationDbContext _context;
        //private readonly IFileProvider _fileProvider;

        public IndexModel(ApplicationDbContext context/*, IFileProvider fileProvider*/)
        {
            _context = context;
            //_fileProvider = fileProvider;
            context.Database.EnsureCreated();//This is not a good place to do this

        }

        public IList<Template> DatabaseFiles { get; private set; }
        //public IDirectoryContents PhysicalFiles { get; private set; }

        public async Task OnGetAsync()
        {
            DatabaseFiles = await _context.Templates.AsNoTracking().ToListAsync();
            //PhysicalFiles = _fileProvider.GetDirectoryContents(string.Empty);
        }

        public async Task<IActionResult> OnGetDownloadDbAsync(int? id)
        {
            if (id == null)
            {
                return Page();
            }

            var requestFile = await _context.Templates.SingleOrDefaultAsync(m => m.Id == id);

            if (requestFile == null)
            {
                return Page();
            }

            // Don't display the untrusted file name in the UI. HTML-encode the value.
            return File(requestFile.Content, MediaTypeNames.Application.Octet, WebUtility.HtmlEncode(requestFile.UntrustedName));
        }

        //public IActionResult OnGetDownloadPhysical(string fileName)
        //{
        //    var downloadFile = _fileProvider.GetFileInfo(fileName);

        //    return PhysicalFile(downloadFile.PhysicalPath, MediaTypeNames.Application.Octet, fileName);
        //}
    }
}

T3/Areas/Templates/Pages/BufferedMultipleFileUploadDb.cshtml
@page
@model T3.Areas.Templates.Pages.BufferedMultipleFileUploadDbModel
@{
    ViewData["Title"] = "Buffered Multiple File Upload (Db)";
}

<h1>Upload multiple buffered files to a database with one file upload control</h1>

<form enctype="multipart/form-data" method="post">
    <dl>
        <dt>
            <label asp-for="FileUpload.Note"></label>
        </dt>
        <dd>
            <input asp-for="FileUpload.Note" type="text" />
            <span asp-validation-for="FileUpload.Note"></span>
        </dd>
        <dt>
            <label asp-for="FileUpload.FormFiles"></label>
        </dt>
        <dd>
            <input asp-for="FileUpload.FormFiles" type="file" multiple />
            <span asp-validation-for="FileUpload.FormFiles"></span>
        </dd>
    </dl>
    <input asp-page-handler="Upload" class="btn" type="submit" value="Upload" />
</form>

<p class="result">
    @Model.Result
</p>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

T3/Areas/Templates/Pages/Index.cshtml
@page
@model T3.Areas.Templates.Pages.IndexModel
@{ ViewData["Title"] = "Upload Files Sample"; }

<h1>Files in the database</h1>
<li>
    Database upload examples
    <ul>
@*        <li><a asp-page="/BufferedSingleFileUploadDb">Upload one buffered file with one file upload control</a></li>*@
        <li><a asp-page="/BufferedMultipleFileUploadDb">Upload multiple buffered files with one file upload control</a></li>
        @*<li><a asp-page="/BufferedDoubleFileUploadDb">Upload two buffered files with two file upload controls</a></li>
        <li><a asp-page="/StreamedSingleFileUploadDb">Stream a file with AJAX to a controller endpoint</a></li>*@
    </ul>
</li>
@if (Model.DatabaseFiles.Count == 0)
{
<p>
    No files are available. Visit one of the file upload scenario pages to upload one or more files.
</p> }
            else
            {
<table class="table">
    <thead>
        <tr>
            <th></th>
            <th>
                @Html.DisplayNameFor(model => model.DatabaseFiles[0].UntrustedName) /
                @Html.DisplayNameFor(model => model.DatabaseFiles[0].Note)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DatabaseFiles[0].UploadDT)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DatabaseFiles[0].Size)
            </th>
            <th>
                FileStreamResult
            </th>
            <th>

            </th>
            <th>

            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var file in Model.DatabaseFiles)
        {
<tr>
    <td>
        <a asp-page="./DeleteDbFile" asp-route-id="@file.Id">Delete</a>
    </td>
    <td>
        <b>@file.UntrustedName</b><br>
        @Html.DisplayFor(modelItem => file.Note)
    </td>
    <td>
        @Html.DisplayFor(modelItem => file.UploadDT)
    </td>
    <td>
        @Html.DisplayFor(modelItem => file.Size)
    </td>
    <td>
        <a asp-page-handler="DownloadDb" asp-route-id="@file.Id">Download</a>
    </td>
    <td>
        @*                    <a asp-page="./ReadDb" asp-route-id="@file.Id">Read</a>*@
        <a asp-page-handler="ReadDb" asp-route-id="@file.Id">Read</a>
    </td>
    <td>
        <a asp-page="./ReadDb" asp-route-id="@file.Id">Read</a>
        @*                  <a asp-page-handler="./ReadDb" asp-route-id="@file.Id">Read</a>*@
    </td>
</tr>
}
    </tbody>
</table>}

T3/Areas/Templates/Pages/ReadDb.cshtml
@page
@model T3.Areas.Templates.Pages.ReadDbModel
@{
}
<h1>Read File</h1>

@if (ViewData["Message"] != null)
{
    //var bPicture = ViewData["bPicture"] as bool;
    if (Model.bPicture)
    {
        <div>Image:</div>
        <div>

            <img src="@ViewData["Message"]" width="250" height="200" alt="Alternate Text" />

        </div>

    }
    else
    {
        <div class="alert alert-success alert-dismissible" style="margin-top:20px">
            @ViewData["Message"]
        </div>

    }
}



<dl>

    <dt>
        @Html.DisplayNameFor(model => model.ReadFile.UntrustedName)
    </dt>
    <dd>
        @Model.ReadFile.UntrustedName
    </dd>
    <dt>
        @Html.DisplayNameFor(model => model.ReadFile.Note)
    </dt>
    <dd>
        @Html.DisplayFor(model => model.ReadFile.Note)
    </dd>
    <dt>
        @Html.DisplayNameFor(model => model.ReadFile.Size)
    </dt>
    <dd>
        @Html.DisplayFor(model => model.ReadFile.Size)
    </dd>
    <dt>
        @Html.DisplayNameFor(model => model.ReadFile.UploadDT)
    </dt>
    <dd>
        @Html.DisplayFor(model => model.ReadFile.UploadDT)
    </dd>
</dl>

<form method="post">
    <input type="hidden" asp-for="ReadFile.Id" />
    <input type="submit" value="Delete" class="btn btn-default" />
</form>